use crate::{CheckResult, CollectResult, ReplayResult, Scar, SpecResult};
use console::style;
use indicatif::{ProgressBar, ProgressStyle};
use std::{env, io::{self, IsTerminal}, time::{Duration, Instant}};

const CAT: &str = " /\\_/\\\n( -.- )  NOT YOU AGAIN\n > ^ <";
pub struct Spinner { bar: Option<ProgressBar>, started: Instant }
impl Spinner { pub fn finish(mut self) -> Duration { if let Some(bar) = self.bar.take() { bar.finish_and_clear(); } self.started.elapsed() } }
impl Drop for Spinner { fn drop(&mut self) { if let Some(bar) = self.bar.take() { bar.finish_and_clear(); } } }
fn interactive() -> bool { env::var_os("NYA_FORCE_TTY").is_some() || (io::stdout().is_terminal() && io::stderr().is_terminal()) }
fn unicode() -> bool { env::var("TERM").as_deref() != Ok("dumb") && env::var_os("NYA_ASCII").is_none() }
fn tint(value: &str, tone: &str) -> String { if env::var_os("NO_COLOR").is_some() || env::var("TERM").as_deref() == Ok("dumb") { return value.into(); } match tone { "brand" => style(value).magenta().bold(), "ok" => style(value).green().bold(), "error" => style(value).red().bold(), "muted" => style(value).dim(), _ => style(value).bold() }.to_string() }
fn count(value: usize, singular: &str) -> String { format!("{value} {singular}{}", if value == 1 { "" } else { "s" }) }
fn header(title: &str) { println!("\n{}\n\n  {}", tint(CAT, "brand"), tint(title, "bold")); }
fn status(ok: bool, label: &str, detail: impl std::fmt::Display) { let mark = if unicode() { if ok { "✓" } else { "×" } } else if ok { "[ok]" } else { "[x]" }; let primary = if ok { format!("{} {}", tint(mark, "ok"), tint(label, "bold")) } else { tint(&format!("{mark} {label}"), "error") }; let detail = detail.to_string(); println!("  {primary}{}", if detail.is_empty() { String::new() } else { format!("  {}", tint(&detail, "muted")) }); }
pub fn begin(json: bool, title: &str, message: &str) -> Spinner { let active = !json && interactive(); if active { header(title); } let bar = active.then(|| { let bar = ProgressBar::new_spinner(); let ticks: &[&str] = if unicode() { &["⠋","⠙","⠹","⠸","⠼","⠴","⠦","⠧","⠇","⠏"] } else { &["-","\\","|","/"] }; bar.set_style(ProgressStyle::with_template("  {spinner:.magenta} {msg}").expect("valid spinner template").tick_strings(ticks)); bar.set_message(message.to_owned()); bar.enable_steady_tick(Duration::from_millis(80)); bar }); Spinner { bar, started: Instant::now() } }
pub fn init(files: &[String]) { if !interactive() { println!("Initialized .nya. Managed instructions: {}.", if files.is_empty() { "none".to_owned() } else { files.join(", ") }); return; } header("Repository initialized"); status(true, ".nya created", "versioned scars ready"); status(true, "Agent instructions", if files.is_empty() { "no managed file found".to_owned() } else { files.join(", ") }); println!(); }
pub fn setup(path: &std::path::Path) { if !interactive() { println!("Configured judge at {}.", path.display()); return; } header("Judge configured"); status(true, "Personal judge selected", path.display()); println!(); }
pub fn remember(value: &Scar) { if !interactive() { println!("Remembered {}: {}", value.id, value.title); return; } header("Scar remembered"); status(true, &value.title, &value.id); println!("    {}\n", value.lesson); }
pub fn recall(values: &[Scar]) { if !interactive() { if values.is_empty() { println!("No relevant scars."); } else { print!("{}", values.iter().map(|s| format!("{}\t{}\n  {}\n", s.id, s.title, s.lesson)).collect::<String>()); } return; } header("Relevant scars"); if values.is_empty() { status(true, "No relevant scars", ""); } else { for scar in values { status(true, &scar.title, &scar.id); println!("    {}", scar.lesson); } } println!(); }
pub fn check(value: &CheckResult, elapsed: Duration) { if !interactive() { if value.passed { println!("No known scars repeated. {} scars checked.", value.scars_checked); } else { print!("{}", value.findings.iter().map(|f| format!("{}:{} [{}] {}\n  {}\n", f.path, f.line, f.scar_id, f.reason, f.evidence)).collect::<String>()); } return; } status(true, "Repository inspected", "diff collected"); status(true, "Relevant scars recalled", count(value.scars_checked, "scar")); if value.passed { status(true, "No known scars repeated", ""); } else { status(false, if value.findings.len() == 1 { "Known scar repeated" } else { "Known scars repeated" }, if value.findings.len() == 1 { String::new() } else { count(value.findings.len(), "recurrence") }); for (index, finding) in value.findings.iter().enumerate() { let mark = if unicode() { "×" } else { "[x]" }; println!("\n  {}\n    {}:{}  {}\n    {}\n\n      {}\n", tint(&format!("{mark} SCAR {}/{}", index + 1, value.findings.len()), "error"), tint(&finding.path, "bold"), finding.line, tint(&finding.scar_id, "muted"), finding.reason, finding.evidence); } println!("  Fix every recurrence and run `nya check` again."); } println!("\n  Checked {} in {:.1}s\n", count(value.scars_checked, "scar"), elapsed.as_secs_f32()); }
pub fn collect(value: &CollectResult, elapsed: Duration) { if !interactive() { let records = value.records.iter().map(|record| format!("{}  {}\t{}\n", if record.classification == "new" { "+" } else { "~" }, record.title, record.source)).collect::<String>(); print!("Collected {} sources and classified {} correction candidates.\nNew scars: {}. Occurrences appended: {}. Insufficient evidence: {}. Ambiguous: {}.\nGitHub: {}.{}\n{}", value.sources_scanned, value.correction_candidates, value.new_scars, value.occurrences_appended, value.insufficient_evidence, value.ambiguous, value.github, if value.dry_run { " Dry run; nothing was written." } else { "" }, records); return; } status(true, "Sources scanned", value.sources_scanned); status(true, "Correction candidates", value.correction_candidates); status(true, "New scars", value.new_scars); status(true, "Recurrences appended", value.occurrences_appended); status(value.ambiguous == 0, "Ambiguous candidates", value.ambiguous); for record in &value.records { status(record.classification == "new", &record.title, &record.source); } println!("\n  GitHub: {}{}  Completed in {:.1}s\n", value.github, if value.dry_run { "  Dry run; nothing written." } else { "" }, elapsed.as_secs_f32()); }
pub fn spec(value: &SpecResult, elapsed: Duration) { if !interactive() { if value.passed { println!("Specification covers all applicable scar requirements. {} scars reviewed.", value.scars_reviewed); } else { for gap in &value.gaps { println!("[{}] {}\n  Add: {}", gap.scar_id, gap.reason, gap.requirement); } } return; } status(true, "Specification files reviewed", value.files_reviewed); status(true, "Relevant scars recalled", count(value.scars_reviewed, "scar")); status(value.passed, if value.passed { "No scar requirements omitted" } else { "Scar requirements omitted" }, if value.passed { String::new() } else { count(value.gaps.len(), "gap") }); for gap in &value.gaps { println!("\n    {}  {}\n      Add: {}", tint(&gap.scar_id, "muted"), gap.reason, gap.requirement); } println!("\n  Reviewed {} in {:.1}s\n", count(value.scars_reviewed, "scar"), elapsed.as_secs_f32()); }
pub fn replay(value: &ReplayResult, elapsed: Duration) { if !interactive() { for case in &value.cases { println!("{}  {}@{}\n  {}", if case.before_repeats && case.after_fixes { "PASS" } else { "FAIL" }, case.scar_id, case.commit, case.reason); } println!("Replayed {} of {} eligible correction pairs.", value.replayed, value.eligible); return; } status(value.passed, "Historical correction pairs", format!("{} replayed, {} eligible", value.replayed, value.eligible)); for case in &value.cases { status(case.before_repeats && case.after_fixes, &case.scar_id, &case.commit); println!("    {}", case.reason); } println!("\n  Completed in {:.1}s\n", elapsed.as_secs_f32()); }
pub fn error(error: &anyhow::Error) { if interactive() { eprintln!("{} {error:#}", tint(if unicode() { "×" } else { "[x]" }, "error")); } else { eprintln!("nya: {error:#}"); } }
